/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "gRPC-IoT.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(gRPCBroker_PostEventRequest, gRPCBroker_PostEventRequest, AUTO)


PB_BIND(gRPCBroker_PostEventReply, gRPCBroker_PostEventReply, AUTO)


PB_BIND(gRPCBroker_EventOutput, gRPCBroker_EventOutput, AUTO)


PB_BIND(gRPCBroker_UpdateDataRequest, gRPCBroker_UpdateDataRequest, 2)


PB_BIND(gRPCBroker_UpdateDataReply, gRPCBroker_UpdateDataReply, AUTO)


PB_BIND(gRPCBroker_DataOutput, gRPCBroker_DataOutput, 2)


PB_BIND(gRPCBroker_GetDataStreamRequest, gRPCBroker_GetDataStreamRequest, AUTO)


PB_BIND(gRPCBroker_GetDataStreamReply, gRPCBroker_GetDataStreamReply, AUTO)


PB_BIND(gRPCBroker_DataInput, gRPCBroker_DataInput, AUTO)


PB_BIND(gRPCBroker_PushNotificationStreamRequest, gRPCBroker_PushNotificationStreamRequest, AUTO)


PB_BIND(gRPCBroker_PushNotificationStreamReply, gRPCBroker_PushNotificationStreamReply, AUTO)


PB_BIND(gRPCBroker_NotificationInput, gRPCBroker_NotificationInput, AUTO)


PB_BIND(gRPCBroker_DeclareConfigurationRequest, gRPCBroker_DeclareConfigurationRequest, AUTO)


PB_BIND(gRPCBroker_DeclareConfigurationReply, gRPCBroker_DeclareConfigurationReply, AUTO)


PB_BIND(gRPCBroker_SetConfigurationStreamRequest, gRPCBroker_SetConfigurationStreamRequest, AUTO)


PB_BIND(gRPCBroker_SetConfigurationStreamReply, gRPCBroker_SetConfigurationStreamReply, AUTO)


PB_BIND(gRPCBroker_Configuration, gRPCBroker_Configuration, AUTO)


PB_BIND(gRPCBroker_DataConfiguration, gRPCBroker_DataConfiguration, AUTO)


PB_BIND(gRPCBroker_EventConfiguration, gRPCBroker_EventConfiguration, AUTO)


PB_BIND(gRPCBroker_ParameterConfiguration, gRPCBroker_ParameterConfiguration, 2)







