/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_GRPCBROKER_GRPC_IOT_PB_H_INCLUDED
#define PB_GRPCBROKER_GRPC_IOT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _gRPCBroker_DataUpdateModeType { 
    gRPCBroker_DataUpdateModeType_AUTO = 0, 
    gRPCBroker_DataUpdateModeType_ASK = 1, 
    gRPCBroker_DataUpdateModeType_INTERVAL = 2 
} gRPCBroker_DataUpdateModeType;

typedef enum _gRPCBroker_EventStatusType { 
    gRPCBroker_EventStatusType_DISABLE = 0, 
    gRPCBroker_EventStatusType_ENABLE = 1 
} gRPCBroker_EventStatusType;

typedef enum _gRPCBroker_ErrorCodeType { 
    gRPCBroker_ErrorCodeType_SUCCESS = 0, 
    gRPCBroker_ErrorCodeType_FAILURE = 1 
} gRPCBroker_ErrorCodeType;

typedef enum _gRPCBroker_DataType { 
    gRPCBroker_DataType_NUMBER = 0, 
    gRPCBroker_DataType_STRING = 1, 
    gRPCBroker_DataType_BOOLEAN = 2, 
    gRPCBroker_DataType_JSON = 3 
} gRPCBroker_DataType;

/* Struct definitions */
typedef struct _gRPCBroker_Configuration { 
    pb_callback_t dataConfiguration; 
    pb_callback_t eventConfiguration; 
    pb_callback_t parameterConfiguration; 
} gRPCBroker_Configuration;

typedef struct _gRPCBroker_GetDataStreamRequest { 
    char dummy_field;
} gRPCBroker_GetDataStreamRequest;

/* Notification */
typedef struct _gRPCBroker_PushNotificationStreamRequest { 
    char dummy_field;
} gRPCBroker_PushNotificationStreamRequest;

typedef struct _gRPCBroker_SetConfigurationStreamRequest { 
    char dummy_field;
} gRPCBroker_SetConfigurationStreamRequest;

typedef struct _gRPCBroker_DataConfiguration { 
    bool has_key;
    char key[128]; 
    bool has_interval;
    int32_t interval; 
    bool has_dataUpdateMode;
    gRPCBroker_DataUpdateModeType dataUpdateMode; 
    bool has_dataType;
    gRPCBroker_DataType dataType; 
} gRPCBroker_DataConfiguration;

typedef struct _gRPCBroker_DataInput { 
    bool has_key;
    char key[128]; 
} gRPCBroker_DataInput;

typedef struct _gRPCBroker_DataOutput { 
    bool has_key;
    char key[128]; 
    bool has_dataType;
    gRPCBroker_DataType dataType; 
    bool has_value;
    char value[128]; 
} gRPCBroker_DataOutput;

typedef struct _gRPCBroker_DeclareConfigurationReply { 
    bool has_errorCode;
    gRPCBroker_ErrorCodeType errorCode; 
} gRPCBroker_DeclareConfigurationReply;

/* Configuration */
typedef struct _gRPCBroker_DeclareConfigurationRequest { 
    bool has_id;
    char id[128]; 
    bool has_configuration;
    gRPCBroker_Configuration configuration; 
} gRPCBroker_DeclareConfigurationRequest;

typedef struct _gRPCBroker_EventConfiguration { 
    bool has_eventStatus;
    gRPCBroker_EventStatusType eventStatus; 
    bool has_key;
    char key[128]; 
} gRPCBroker_EventConfiguration;

typedef struct _gRPCBroker_EventOutput { 
    bool has_key;
    char key[128]; 
} gRPCBroker_EventOutput;

typedef struct _gRPCBroker_NotificationInput { 
    bool has_key;
    char key[128]; 
} gRPCBroker_NotificationInput;

typedef struct _gRPCBroker_ParameterConfiguration { 
    bool has_key;
    char key[128]; 
    bool has_value;
    char value[128]; 
    bool has_dataType;
    gRPCBroker_DataType dataType; 
} gRPCBroker_ParameterConfiguration;

typedef struct _gRPCBroker_PostEventReply { 
    bool has_errorCode;
    gRPCBroker_ErrorCodeType errorCode; 
} gRPCBroker_PostEventReply;

typedef struct _gRPCBroker_SetConfigurationStreamReply { 
    bool has_configuration;
    gRPCBroker_Configuration configuration; 
} gRPCBroker_SetConfigurationStreamReply;

typedef struct _gRPCBroker_UpdateDataReply { 
    bool has_errorCode;
    gRPCBroker_ErrorCodeType errorCode; 
} gRPCBroker_UpdateDataReply;

typedef struct _gRPCBroker_GetDataStreamReply { 
    bool has_dataInput;
    gRPCBroker_DataInput dataInput; 
} gRPCBroker_GetDataStreamReply;

/* Event */
typedef struct _gRPCBroker_PostEventRequest { 
    bool has_eventOutput;
    gRPCBroker_EventOutput eventOutput; 
} gRPCBroker_PostEventRequest;

typedef struct _gRPCBroker_PushNotificationStreamReply { 
    bool has_notificationInput;
    gRPCBroker_NotificationInput notificationInput; 
} gRPCBroker_PushNotificationStreamReply;

/* Data */
typedef struct _gRPCBroker_UpdateDataRequest { 
    bool has_dataOutput;
    gRPCBroker_DataOutput dataOutput; 
} gRPCBroker_UpdateDataRequest;


/* Helper constants for enums */
#define _gRPCBroker_DataUpdateModeType_MIN gRPCBroker_DataUpdateModeType_AUTO
#define _gRPCBroker_DataUpdateModeType_MAX gRPCBroker_DataUpdateModeType_INTERVAL
#define _gRPCBroker_DataUpdateModeType_ARRAYSIZE ((gRPCBroker_DataUpdateModeType)(gRPCBroker_DataUpdateModeType_INTERVAL+1))

#define _gRPCBroker_EventStatusType_MIN gRPCBroker_EventStatusType_DISABLE
#define _gRPCBroker_EventStatusType_MAX gRPCBroker_EventStatusType_ENABLE
#define _gRPCBroker_EventStatusType_ARRAYSIZE ((gRPCBroker_EventStatusType)(gRPCBroker_EventStatusType_ENABLE+1))

#define _gRPCBroker_ErrorCodeType_MIN gRPCBroker_ErrorCodeType_SUCCESS
#define _gRPCBroker_ErrorCodeType_MAX gRPCBroker_ErrorCodeType_FAILURE
#define _gRPCBroker_ErrorCodeType_ARRAYSIZE ((gRPCBroker_ErrorCodeType)(gRPCBroker_ErrorCodeType_FAILURE+1))

#define _gRPCBroker_DataType_MIN gRPCBroker_DataType_NUMBER
#define _gRPCBroker_DataType_MAX gRPCBroker_DataType_JSON
#define _gRPCBroker_DataType_ARRAYSIZE ((gRPCBroker_DataType)(gRPCBroker_DataType_JSON+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define gRPCBroker_PostEventRequest_init_default {false, gRPCBroker_EventOutput_init_default}
#define gRPCBroker_PostEventReply_init_default   {false, _gRPCBroker_ErrorCodeType_MIN}
#define gRPCBroker_EventOutput_init_default      {false, ""}
#define gRPCBroker_UpdateDataRequest_init_default {false, gRPCBroker_DataOutput_init_default}
#define gRPCBroker_UpdateDataReply_init_default  {false, _gRPCBroker_ErrorCodeType_MIN}
#define gRPCBroker_DataOutput_init_default       {false, "", false, _gRPCBroker_DataType_MIN, false, ""}
#define gRPCBroker_GetDataStreamRequest_init_default {0}
#define gRPCBroker_GetDataStreamReply_init_default {false, gRPCBroker_DataInput_init_default}
#define gRPCBroker_DataInput_init_default        {false, ""}
#define gRPCBroker_PushNotificationStreamRequest_init_default {0}
#define gRPCBroker_PushNotificationStreamReply_init_default {false, gRPCBroker_NotificationInput_init_default}
#define gRPCBroker_NotificationInput_init_default {false, ""}
#define gRPCBroker_DeclareConfigurationRequest_init_default {false, "", false, gRPCBroker_Configuration_init_default}
#define gRPCBroker_DeclareConfigurationReply_init_default {false, _gRPCBroker_ErrorCodeType_MIN}
#define gRPCBroker_SetConfigurationStreamRequest_init_default {0}
#define gRPCBroker_SetConfigurationStreamReply_init_default {false, gRPCBroker_Configuration_init_default}
#define gRPCBroker_Configuration_init_default    {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define gRPCBroker_DataConfiguration_init_default {false, "", false, 0, false, _gRPCBroker_DataUpdateModeType_MIN, false, _gRPCBroker_DataType_MIN}
#define gRPCBroker_EventConfiguration_init_default {false, _gRPCBroker_EventStatusType_MIN, false, ""}
#define gRPCBroker_ParameterConfiguration_init_default {false, "", false, "", false, _gRPCBroker_DataType_MIN}
#define gRPCBroker_PostEventRequest_init_zero    {false, gRPCBroker_EventOutput_init_zero}
#define gRPCBroker_PostEventReply_init_zero      {false, _gRPCBroker_ErrorCodeType_MIN}
#define gRPCBroker_EventOutput_init_zero         {false, ""}
#define gRPCBroker_UpdateDataRequest_init_zero   {false, gRPCBroker_DataOutput_init_zero}
#define gRPCBroker_UpdateDataReply_init_zero     {false, _gRPCBroker_ErrorCodeType_MIN}
#define gRPCBroker_DataOutput_init_zero          {false, "", false, _gRPCBroker_DataType_MIN, false, ""}
#define gRPCBroker_GetDataStreamRequest_init_zero {0}
#define gRPCBroker_GetDataStreamReply_init_zero  {false, gRPCBroker_DataInput_init_zero}
#define gRPCBroker_DataInput_init_zero           {false, ""}
#define gRPCBroker_PushNotificationStreamRequest_init_zero {0}
#define gRPCBroker_PushNotificationStreamReply_init_zero {false, gRPCBroker_NotificationInput_init_zero}
#define gRPCBroker_NotificationInput_init_zero   {false, ""}
#define gRPCBroker_DeclareConfigurationRequest_init_zero {false, "", false, gRPCBroker_Configuration_init_zero}
#define gRPCBroker_DeclareConfigurationReply_init_zero {false, _gRPCBroker_ErrorCodeType_MIN}
#define gRPCBroker_SetConfigurationStreamRequest_init_zero {0}
#define gRPCBroker_SetConfigurationStreamReply_init_zero {false, gRPCBroker_Configuration_init_zero}
#define gRPCBroker_Configuration_init_zero       {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define gRPCBroker_DataConfiguration_init_zero   {false, "", false, 0, false, _gRPCBroker_DataUpdateModeType_MIN, false, _gRPCBroker_DataType_MIN}
#define gRPCBroker_EventConfiguration_init_zero  {false, _gRPCBroker_EventStatusType_MIN, false, ""}
#define gRPCBroker_ParameterConfiguration_init_zero {false, "", false, "", false, _gRPCBroker_DataType_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define gRPCBroker_Configuration_dataConfiguration_tag 1
#define gRPCBroker_Configuration_eventConfiguration_tag 2
#define gRPCBroker_Configuration_parameterConfiguration_tag 3
#define gRPCBroker_DataConfiguration_key_tag     1
#define gRPCBroker_DataConfiguration_interval_tag 2
#define gRPCBroker_DataConfiguration_dataUpdateMode_tag 3
#define gRPCBroker_DataConfiguration_dataType_tag 4
#define gRPCBroker_DataInput_key_tag             1
#define gRPCBroker_DataOutput_key_tag            1
#define gRPCBroker_DataOutput_dataType_tag       2
#define gRPCBroker_DataOutput_value_tag          3
#define gRPCBroker_DeclareConfigurationReply_errorCode_tag 1
#define gRPCBroker_DeclareConfigurationRequest_id_tag 1
#define gRPCBroker_DeclareConfigurationRequest_configuration_tag 2
#define gRPCBroker_EventConfiguration_eventStatus_tag 1
#define gRPCBroker_EventConfiguration_key_tag    2
#define gRPCBroker_EventOutput_key_tag           1
#define gRPCBroker_NotificationInput_key_tag     1
#define gRPCBroker_ParameterConfiguration_key_tag 1
#define gRPCBroker_ParameterConfiguration_value_tag 2
#define gRPCBroker_ParameterConfiguration_dataType_tag 3
#define gRPCBroker_PostEventReply_errorCode_tag  1
#define gRPCBroker_SetConfigurationStreamReply_configuration_tag 1
#define gRPCBroker_UpdateDataReply_errorCode_tag 1
#define gRPCBroker_GetDataStreamReply_dataInput_tag 1
#define gRPCBroker_PostEventRequest_eventOutput_tag 1
#define gRPCBroker_PushNotificationStreamReply_notificationInput_tag 1
#define gRPCBroker_UpdateDataRequest_dataOutput_tag 1

/* Struct field encoding specification for nanopb */
#define gRPCBroker_PostEventRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  eventOutput,       1)
#define gRPCBroker_PostEventRequest_CALLBACK NULL
#define gRPCBroker_PostEventRequest_DEFAULT NULL
#define gRPCBroker_PostEventRequest_eventOutput_MSGTYPE gRPCBroker_EventOutput

#define gRPCBroker_PostEventReply_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    errorCode,         1)
#define gRPCBroker_PostEventReply_CALLBACK NULL
#define gRPCBroker_PostEventReply_DEFAULT NULL

#define gRPCBroker_EventOutput_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   key,               1)
#define gRPCBroker_EventOutput_CALLBACK NULL
#define gRPCBroker_EventOutput_DEFAULT NULL

#define gRPCBroker_UpdateDataRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  dataOutput,        1)
#define gRPCBroker_UpdateDataRequest_CALLBACK NULL
#define gRPCBroker_UpdateDataRequest_DEFAULT NULL
#define gRPCBroker_UpdateDataRequest_dataOutput_MSGTYPE gRPCBroker_DataOutput

#define gRPCBroker_UpdateDataReply_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    errorCode,         1)
#define gRPCBroker_UpdateDataReply_CALLBACK NULL
#define gRPCBroker_UpdateDataReply_DEFAULT NULL

#define gRPCBroker_DataOutput_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, UENUM,    dataType,          2) \
X(a, STATIC,   OPTIONAL, STRING,   value,             3)
#define gRPCBroker_DataOutput_CALLBACK NULL
#define gRPCBroker_DataOutput_DEFAULT NULL

#define gRPCBroker_GetDataStreamRequest_FIELDLIST(X, a) \

#define gRPCBroker_GetDataStreamRequest_CALLBACK NULL
#define gRPCBroker_GetDataStreamRequest_DEFAULT NULL

#define gRPCBroker_GetDataStreamReply_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  dataInput,         1)
#define gRPCBroker_GetDataStreamReply_CALLBACK NULL
#define gRPCBroker_GetDataStreamReply_DEFAULT NULL
#define gRPCBroker_GetDataStreamReply_dataInput_MSGTYPE gRPCBroker_DataInput

#define gRPCBroker_DataInput_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   key,               1)
#define gRPCBroker_DataInput_CALLBACK NULL
#define gRPCBroker_DataInput_DEFAULT NULL

#define gRPCBroker_PushNotificationStreamRequest_FIELDLIST(X, a) \

#define gRPCBroker_PushNotificationStreamRequest_CALLBACK NULL
#define gRPCBroker_PushNotificationStreamRequest_DEFAULT NULL

#define gRPCBroker_PushNotificationStreamReply_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  notificationInput,   1)
#define gRPCBroker_PushNotificationStreamReply_CALLBACK NULL
#define gRPCBroker_PushNotificationStreamReply_DEFAULT NULL
#define gRPCBroker_PushNotificationStreamReply_notificationInput_MSGTYPE gRPCBroker_NotificationInput

#define gRPCBroker_NotificationInput_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   key,               1)
#define gRPCBroker_NotificationInput_CALLBACK NULL
#define gRPCBroker_NotificationInput_DEFAULT NULL

#define gRPCBroker_DeclareConfigurationRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   id,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  configuration,     2)
#define gRPCBroker_DeclareConfigurationRequest_CALLBACK NULL
#define gRPCBroker_DeclareConfigurationRequest_DEFAULT NULL
#define gRPCBroker_DeclareConfigurationRequest_configuration_MSGTYPE gRPCBroker_Configuration

#define gRPCBroker_DeclareConfigurationReply_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    errorCode,         1)
#define gRPCBroker_DeclareConfigurationReply_CALLBACK NULL
#define gRPCBroker_DeclareConfigurationReply_DEFAULT NULL

#define gRPCBroker_SetConfigurationStreamRequest_FIELDLIST(X, a) \

#define gRPCBroker_SetConfigurationStreamRequest_CALLBACK NULL
#define gRPCBroker_SetConfigurationStreamRequest_DEFAULT NULL

#define gRPCBroker_SetConfigurationStreamReply_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  configuration,     1)
#define gRPCBroker_SetConfigurationStreamReply_CALLBACK NULL
#define gRPCBroker_SetConfigurationStreamReply_DEFAULT NULL
#define gRPCBroker_SetConfigurationStreamReply_configuration_MSGTYPE gRPCBroker_Configuration

#define gRPCBroker_Configuration_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  dataConfiguration,   1) \
X(a, CALLBACK, REPEATED, MESSAGE,  eventConfiguration,   2) \
X(a, CALLBACK, REPEATED, MESSAGE,  parameterConfiguration,   3)
#define gRPCBroker_Configuration_CALLBACK pb_default_field_callback
#define gRPCBroker_Configuration_DEFAULT NULL
#define gRPCBroker_Configuration_dataConfiguration_MSGTYPE gRPCBroker_DataConfiguration
#define gRPCBroker_Configuration_eventConfiguration_MSGTYPE gRPCBroker_EventConfiguration
#define gRPCBroker_Configuration_parameterConfiguration_MSGTYPE gRPCBroker_ParameterConfiguration

#define gRPCBroker_DataConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, INT32,    interval,          2) \
X(a, STATIC,   OPTIONAL, UENUM,    dataUpdateMode,    3) \
X(a, STATIC,   OPTIONAL, UENUM,    dataType,          4)
#define gRPCBroker_DataConfiguration_CALLBACK NULL
#define gRPCBroker_DataConfiguration_DEFAULT NULL

#define gRPCBroker_EventConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    eventStatus,       1) \
X(a, STATIC,   OPTIONAL, STRING,   key,               2)
#define gRPCBroker_EventConfiguration_CALLBACK NULL
#define gRPCBroker_EventConfiguration_DEFAULT NULL

#define gRPCBroker_ParameterConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, STRING,   value,             2) \
X(a, STATIC,   OPTIONAL, UENUM,    dataType,          3)
#define gRPCBroker_ParameterConfiguration_CALLBACK NULL
#define gRPCBroker_ParameterConfiguration_DEFAULT NULL

extern const pb_msgdesc_t gRPCBroker_PostEventRequest_msg;
extern const pb_msgdesc_t gRPCBroker_PostEventReply_msg;
extern const pb_msgdesc_t gRPCBroker_EventOutput_msg;
extern const pb_msgdesc_t gRPCBroker_UpdateDataRequest_msg;
extern const pb_msgdesc_t gRPCBroker_UpdateDataReply_msg;
extern const pb_msgdesc_t gRPCBroker_DataOutput_msg;
extern const pb_msgdesc_t gRPCBroker_GetDataStreamRequest_msg;
extern const pb_msgdesc_t gRPCBroker_GetDataStreamReply_msg;
extern const pb_msgdesc_t gRPCBroker_DataInput_msg;
extern const pb_msgdesc_t gRPCBroker_PushNotificationStreamRequest_msg;
extern const pb_msgdesc_t gRPCBroker_PushNotificationStreamReply_msg;
extern const pb_msgdesc_t gRPCBroker_NotificationInput_msg;
extern const pb_msgdesc_t gRPCBroker_DeclareConfigurationRequest_msg;
extern const pb_msgdesc_t gRPCBroker_DeclareConfigurationReply_msg;
extern const pb_msgdesc_t gRPCBroker_SetConfigurationStreamRequest_msg;
extern const pb_msgdesc_t gRPCBroker_SetConfigurationStreamReply_msg;
extern const pb_msgdesc_t gRPCBroker_Configuration_msg;
extern const pb_msgdesc_t gRPCBroker_DataConfiguration_msg;
extern const pb_msgdesc_t gRPCBroker_EventConfiguration_msg;
extern const pb_msgdesc_t gRPCBroker_ParameterConfiguration_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define gRPCBroker_PostEventRequest_fields &gRPCBroker_PostEventRequest_msg
#define gRPCBroker_PostEventReply_fields &gRPCBroker_PostEventReply_msg
#define gRPCBroker_EventOutput_fields &gRPCBroker_EventOutput_msg
#define gRPCBroker_UpdateDataRequest_fields &gRPCBroker_UpdateDataRequest_msg
#define gRPCBroker_UpdateDataReply_fields &gRPCBroker_UpdateDataReply_msg
#define gRPCBroker_DataOutput_fields &gRPCBroker_DataOutput_msg
#define gRPCBroker_GetDataStreamRequest_fields &gRPCBroker_GetDataStreamRequest_msg
#define gRPCBroker_GetDataStreamReply_fields &gRPCBroker_GetDataStreamReply_msg
#define gRPCBroker_DataInput_fields &gRPCBroker_DataInput_msg
#define gRPCBroker_PushNotificationStreamRequest_fields &gRPCBroker_PushNotificationStreamRequest_msg
#define gRPCBroker_PushNotificationStreamReply_fields &gRPCBroker_PushNotificationStreamReply_msg
#define gRPCBroker_NotificationInput_fields &gRPCBroker_NotificationInput_msg
#define gRPCBroker_DeclareConfigurationRequest_fields &gRPCBroker_DeclareConfigurationRequest_msg
#define gRPCBroker_DeclareConfigurationReply_fields &gRPCBroker_DeclareConfigurationReply_msg
#define gRPCBroker_SetConfigurationStreamRequest_fields &gRPCBroker_SetConfigurationStreamRequest_msg
#define gRPCBroker_SetConfigurationStreamReply_fields &gRPCBroker_SetConfigurationStreamReply_msg
#define gRPCBroker_Configuration_fields &gRPCBroker_Configuration_msg
#define gRPCBroker_DataConfiguration_fields &gRPCBroker_DataConfiguration_msg
#define gRPCBroker_EventConfiguration_fields &gRPCBroker_EventConfiguration_msg
#define gRPCBroker_ParameterConfiguration_fields &gRPCBroker_ParameterConfiguration_msg

/* Maximum encoded size of messages (where known) */
/* gRPCBroker_DeclareConfigurationRequest_size depends on runtime parameters */
/* gRPCBroker_SetConfigurationStreamReply_size depends on runtime parameters */
/* gRPCBroker_Configuration_size depends on runtime parameters */
#define gRPCBroker_DataConfiguration_size        145
#define gRPCBroker_DataInput_size                130
#define gRPCBroker_DataOutput_size               262
#define gRPCBroker_DeclareConfigurationReply_size 2
#define gRPCBroker_EventConfiguration_size       132
#define gRPCBroker_EventOutput_size              130
#define gRPCBroker_GetDataStreamReply_size       133
#define gRPCBroker_GetDataStreamRequest_size     0
#define gRPCBroker_NotificationInput_size        130
#define gRPCBroker_ParameterConfiguration_size   262
#define gRPCBroker_PostEventReply_size           2
#define gRPCBroker_PostEventRequest_size         133
#define gRPCBroker_PushNotificationStreamReply_size 133
#define gRPCBroker_PushNotificationStreamRequest_size 0
#define gRPCBroker_SetConfigurationStreamRequest_size 0
#define gRPCBroker_UpdateDataReply_size          2
#define gRPCBroker_UpdateDataRequest_size        265

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
